name: influmeet
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_analytics: ^10.1.0
  cupertino_icons: ^1.0.6
  flutter_swiper_null_safety: ^1.0.2  # Añadida dependencia para la funcionalidad de swipe
  flip_card: ^0.7.0
  flutter_facebook_auth: ^7.0.0
  permission_handler: ^9.0.0
  awesome_notifications: ^0.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.17.5
  font_awesome_flutter: ^10.1.0 # Asegúrate de utilizar la última versión
  tcard: ^1.3.1  # Añadida dependencia para la funcionalidad de swipe de tarjetas
  fluttertoast: ^8.0.9  # Añadida dependencia para mostrar mensajes temporales
  image_picker: ^0.8.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/influagency_logo.png
    - assets/images/google_icon.png
    - assets/images/correo_icon.png
    - assets/images/facebook_icon.png
    - assets/images/jp.png
    - assets/images/hg.png
    - assets/images/EM.jpeg
    - assets/images/arrow_back.png
    - assets/images/like_icon.png
    - assets/images/dislike_icon.png
    - assets/images/information_icon.png
    - assets/images/musica.jpg
    - assets/images/deportes.jpg
    - assets/images/humor.jpg
    - assets/images/entretenimiento.jpg
    - assets/images/tecnologia.jpg
    - assets/images/gastronomia.jpg
    - assets/images/belleza.jpg
  

