name: influmeet
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_analytics: ^10.1.0
  cupertino_icons: ^1.0.6
  flutter_swiper_null_safety: ^1.0.2  # Añadida dependencia para la funcionalidad de swipe

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/influagency_logo.png
    - assets/images/google_icon.png
    - assets/images/correo_icon.png
    - assets/images/facebook_icon.png
    - assets/images/jp.png
    - assets/images/hg.png
    - assets/images/EM.jpeg

