// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnDHAXDq2q0YfJzFiYRm-VaDUTEWThOg8',
    appId: '1:886077325287:web:0ff1bd19fd4b39f4580742',
    messagingSenderId: '886077325287',
    projectId: 'influagency-bddba',
    authDomain: 'influagency-bddba.firebaseapp.com',
    storageBucket: 'influagency-bddba.appspot.com',
    measurementId: 'G-8WLP8TGKK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6U62zTamOAZs-qv18g6O1bwqRUxxPoXo',
    appId: '1:886077325287:android:9dcfb382f2ab691c580742',
    messagingSenderId: '886077325287',
    projectId: 'influagency-bddba',
    storageBucket: 'influagency-bddba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa2QdYIMMM8sYieqhJM7K6_2CUgMzkN0Q',
    appId: '1:886077325287:ios:f55a09771f0c34d7580742',
    messagingSenderId: '886077325287',
    projectId: 'influagency-bddba',
    storageBucket: 'influagency-bddba.appspot.com',
    iosBundleId: 'com.example.influmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa2QdYIMMM8sYieqhJM7K6_2CUgMzkN0Q',
    appId: '1:886077325287:ios:f55a09771f0c34d7580742',
    messagingSenderId: '886077325287',
    projectId: 'influagency-bddba',
    storageBucket: 'influagency-bddba.appspot.com',
    iosBundleId: 'com.example.influmeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnDHAXDq2q0YfJzFiYRm-VaDUTEWThOg8',
    appId: '1:886077325287:web:79505f88fe05071d580742',
    messagingSenderId: '886077325287',
    projectId: 'influagency-bddba',
    authDomain: 'influagency-bddba.firebaseapp.com',
    storageBucket: 'influagency-bddba.appspot.com',
    measurementId: 'G-Y1PVJSWRS9',
  );

}